[package]
publish = false
name = "php-ext-wasm-cargo-serde-example"
version = "1.0.0"
edition = "2018"

[lib]
path = "serde.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
