name: Documentation

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:

jobs:
  test:
    name: Documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: 7.4-composer-${{ hashFiles('**/composer.json') }}
      - name: Configure
        run: |
          cd ext
          phpize
          ./configure
      - name: Build
        run: |
          make documentation
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.phpdoc/build
      - name: Archive
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          retention-days: 3
          path: |
            ./target/doc
