name: Lint

on:
  # TODO(jubianchi): Remove this before merge
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cd ext
          phpize
          ./configure
      - name: Lint PHP
        run: |
          make lint
