name: Lint

on:
  # TODO(jubianchi): Remove this before merge
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install Wasmer
        run: |
          curl https://get.wasmer.io -sSfL | sh
          source /home/runner/.wasmer/wasmer.sh
          sudo mkdir -p /usr/local/lib/pkgconfig
          wasmer config --pkg-config | sudo tee /usr/local/lib/pkgconfig/wasmer.pc
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          phpize
          ./configure
      - name: Lint
        run: |
          make lint
